on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        scale: [1, 3, 5, 10]
        extension: ["postgres", "citus"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.${{ matrix.extension }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: h3nryc0ding/dbdi:${{ matrix.extension }}-${{ matrix.scale }}
          build-args: SCALE=${{ matrix.scale }}