on:
  workflow_dispatch:
    inputs:
      scalefactor:
        description: 'Scale factor for dbgen'
        required: true
        default: '1'
      query:
        description: 'Query to run'
        default: 'SELECT * FROM dates;'
        required: true

jobs:
  build_generate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ssb-dbgen

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build dbgen
      run: |
        cmake . && cmake --build .
        chmod +x dbgen

    - name: Generate data with Scale Factor ${{ github.event.inputs.scalefactor }}
      run: |
        ./dbgen -v -s ${{ github.event.inputs.scalefactor }}

    - name: Archive generated data
      uses: actions/upload-artifact@v2
      with:
        name: data
        path: "ssb-dbgen/*.tbl"
        if-no-files-found: error
  
  benchmark:
    needs: build_generate
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: ssb
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download generated data
      uses: actions/download-artifact@v2
      with:
        name: data

    - name: Initialize database
      working-directory: sql/init
      run: |
        psql -h localhost -p 5432 -U postgres ssb -f tables.sql
        psql -h localhost -p 5432 -U postgres ssb -f load.sql

    - name: Run query
      run: |
        psql -h localhost -p 5432 -U postgres ssb --command ${{ github.event.inputs.query }}