on:
  workflow_dispatch:
    inputs:
      scalefactor:
        description: 'Scale factor for dbgen'
        required: true
        default: '1'
      query:
        description: 'Query to run'
        default: 'SELECT * FROM dates;'
        required: true

jobs:
  build_generate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ssb-dbgen

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build dbgen
      run: |
        cmake . && cmake --build .
        chmod +x dbgen

    - name: Generate data with Scale Factor ${{ github.event.inputs.scalefactor }}
      run: |
        ./dbgen -v -s ${{ github.event.inputs.scalefactor }}

    - name: Archive generated data
      uses: actions/upload-artifact@v2
      with:
        name: data
        path: "ssb-dbgen/*.tbl"
        if-no-files-found: error
  
  benchmark:
    needs: build_generate
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: ssb
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download generated data
      uses: actions/download-artifact@v2
      with:
        name: data
        path: /tmp

    - name: Initialize database
      run: |
        psql -h localhost -p 5432 -U postgres ssb -f ./sql/init/tables.sql
        psql -h localhost -p 5432 -U postgres ssb -c "TRUNCATE customer;"
        psql -h localhost -p 5432 -U postgres ssb -c "TRUNCATE dates;"
        psql -h localhost -p 5432 -U postgres ssb -c "TRUNCATE part;"
        psql -h localhost -p 5432 -U postgres ssb -c "TRUNCATE supplier;"
        psql -h localhost -p 5432 -U postgres ssb -c "TRUNCATE lineorder;"
        psql -h localhost -p 5432 -U postgres ssb -c "COPY customer FROM stdin DELIMITER '|';" < /tmp/customer.tbl
        psql -h localhost -p 5432 -U postgres ssb -c "COPY dates FROM stdin DELIMITER '|';" < /tmp/date.tbl
        psql -h localhost -p 5432 -U postgres ssb -c "COPY part FROM stdin DELIMITER '|';" < /tmp/part.tbl
        psql -h localhost -p 5432 -U postgres ssb -c "COPY supplier FROM stdin DELIMITER '|';" < /tmp/supplier.tbl
        psql -h localhost -p 5432 -U postgres ssb -c "COPY lineorder FROM stdin DELIMITER '|';" < /tmp/lineorder.tbl


    - name: Benchmark
      working-directory: sql/queries
      run: ./benchmark.sh

    - name: Upload .csv results
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: sql/queries/*.csv
        if-no-files-found: error
        